{% set name = "pgspecial" %}
{% set version = "1.10.0" %}
{% set sha256 = "eadb0108cdbcf8b38a69bcc9e403b352dbd6d30622e417f48e659180150ee1b6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - click >=4.1
    - sqlparse >=0.1.19
    - psycopg2

test:
  imports:
    - pgspecial
    - pgspecial.help

about:
  home: http://pgcli.com
  license: BSD-3-Clause
  license_family: BSD
  # xref: https://github.com/dbcli/pgspecial/pull/38
  # license_file: LICENSE.txt
  summary: 'Meta-commands handler for Postgres Database.'
  dev_url: https://github.com/dbcli/pgspecial

extra:
  recipe-maintainers:
    - mariusvniekerk
