# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_python2.7
    - CONFIG=osx_python3.6
    - CONFIG=osx_python3.7

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "q5+ZB3LizVBfadHPycewePGKp6+Witw/0snl06iw9uh+qKUsNNawOdJ53SHOwi48+8Sw+KlWutFpvTMEJ1jgfkLoU05Alj1P2e1dVXdldpsbpa9RAIbrGa+vYDolrDyYWbA03OKoRB0wsUIDSx4cQqhnjLQS+YOYAxsf6noXQfky78pjNnfYZDb2kN1Q+iyMBMpcpoxgkF01Q5gUj1VGFmEk8bHdvLeeggdBaDnbgDOngA7tgQ1kHE38etU3YEIr2FDpmUlXBeypV5paXv1kSMGUoBoK0F7r8Fvt6BciiQQUQ1f0/NBCgcyfTp5+es8v482v/YaG6fo4n7nvtCK9oCLqNffUZuCKgNDnmu7bZKO7Cf9GxyC/l0yQtZWA5SwdDmO8T+Nzq1WLxOUc9CNnFa2sX/FwWOjjDiXBBTFcyLlAvziUAa6PuS+E5IR386SiJAa/cfXotrQXkbCt5PRqo/gqhrP0AZvwAoUxlHp2hNSis4Rxp99bMCrgVbq+jA2sUj1rW17LVKbHcqZX1G2aJV/KeFXncgnqx7jwOE8EksOIBNuDO1BNZYEgr4a2uqk0e4YMwuAFP+I4gJX39p+iKOrO+bnOCBwQThuT+uhM+OBSj089ls1KdZ0h0SEgr2Dc8VsKDlMr/j2J3QSLYvQ28HwtuIonobhl4cmplk7KQFs="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
