travis:
  secure:
    BINSTAR_TOKEN: GXh7IYI9pFCC4sb/mKiQy1Xy3FXMe5AgA8Sqzas28ZWWoCqMu8j10VrBa3I9ebjcaDhk8YbPd2dvouIxCSTgS9petBylzadr6Od2dITt3PAWCSv+54BmChspm85iWxSYR6PJ6WcMN0fMgRx5adTT+C1BrfHsRGsHXvE+7WZNlxxaWXqLsUtkfqTgp/obyK9/k+i3a+coRewJG9px2izbOweJ86qreViZJr/oQZcko1frR0iDCiKquZ2URGILfDYT3sruDc8m+uSmWqKDRdVh9AaVr1555fEaZcobkiT7FufrYLNw+/SG0RKHg/bWih9W8sjLKSkNLbmCW/c2IeWlt+u9ErhI3gmQ3Z7+a3/aKpQI8IBDPXu4jfvqaherLlXp2Wt6yukCNLjPNnZ/JXUMGYPKzhaGzPj+LdoMyScZTbPSlzGQxB15u9izCQU13iLvWeC+ClCC7zJZru2s/JI9yoZW0byzff3T+dwbhElpTFU8CtDjEYcfYXDVAVIye6rGMKzdvp8pe1+bK+lPkDf3OiXaNfZ9CDSq1ZcBOe8m2mKlhcecRzFn4CrR1vgfwt3JamrJVDSOT0b9CYPTn62LnI6Fl2d/pInAaze3QfI/A3lKQhFq1FBwkpokhBn1GaqrmwMPRP7pVNwsrsW8sVnNPINJH2Y3QcJbb9GedNd8iDw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
